# ssh -R 5060:localhost:5060 root@api.welcomizer.com
POST https://api.welcomizer.com/notify
Content-Type: application/json

{
  "contactFirstName": "Pedro",
  "contactLastName": "Palhari",
  "contactEmail": "gadfaria@gmail.com",
  "appName": "Gabriel's App"
}