# ssh -R 5060:localhost:5060 root@api.welcomizer.com
POST https://api.welcomizer.com/notify
Content-Type: application/json

{
  "contactFirstName": "Pedro",
  "contactLastName": "Palhari",
  "contactEmail": "pedropalhari@gmail.com",
  "appName": "Gabriel's App",
  "firebaseUserId": "NDBJckQhF6hlkkH3GCaKDDwJ6NQ2"
}